# Generated by Django 4.2.7 on 2023-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail_image', models.ImageField(blank=True, default='project_manager/default_image.jpg', upload_to='upload/')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('planning', 'Planning'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='not_started', max_length=11)),
                ('current_version', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
